# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-15 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20190115_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='menu',
            field=models.ManyToManyField(to='menu.Menu'),
        ),
    ]
