# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-15 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20190115_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu',
            field=models.ManyToManyField(to='menu.Item'),
        ),
    ]
