# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-15 21:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20190115_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_on_menu',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='has_items',
        ),
        migrations.AddField(
            model_name='item',
            name='menus',
            field=models.ManyToManyField(to='menu.Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 15, 13, 28, 36, 445403)),
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
