# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-15 21:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20190115_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 15, 13, 42, 45, 733098)),
        ),
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(related_name='items', to='menu.Item'),
        ),
    ]
